### ISSUE TITLE
Proposal: Move this to AEGEE namespace

### ISSUE THREAD

**Issue by serge1peshcoff** [lesteenman/AgoraUpload#34]
Hey @lesteenman,

We (as ITC) are currently trying to move every repository containing things related to AEGEE to https://github.com/AEGEE namespace, so we would have every piece of AEGEE's IT in one place.
As Agora Upload tool is still is in active use, I propose to move it under AEGEE namespace, so it can be easily located. What do you think?

(Opening this issue here as I don't know other ways to contact you.)

Yours,
Sergey Peshkov,
ITC speaker.

**Comment by lesteenman** [comment]
Hi Sergey,

I actively watch my repositories, so this is the preferred way to contact me regarding any! I'm completely fine with it being moved to AEGEE. To be honest, I had no idea it was still in active use, fun to hear!

What teams should have access to the repository? When I try transferring ownership, that's the question I get.

**Comment by serge1peshcoff** [comment]
I can make it either private (and allow the access to AEGEE owners and Chair ITs and you) or public. Both can be done easily, as we as an NGO have the unlimited private repositories.

What do you think can be the best?

**Comment by lesteenman** [comment]
I would prefer it remaining public. I just noticed I don't need to say what teams have access, so I've transferred it to AEGEE/AgoraUpload. If there are more required changes from me, just let me know, but I think AEGEE can now manage it.

**Comment by serge1peshcoff** [comment]
Awesome, thanks <3
